# Generated by Django 3.2.7 on 2021-11-21 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=30, null=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ciudades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('clima', models.CharField(max_length=30)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hoteles',
            fields=[
                ('nit_hotel', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('fechainicio', models.CharField(max_length=20)),
                ('fechafinal', models.CharField(max_length=20)),
                ('tarifa', models.CharField(max_length=20)),
                ('ciudad_hotel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plantur.ciudades')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('cedula', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('celular', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=40)),
                ('direccion', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('nit_transporte', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=40)),
                ('nombre', models.CharField(max_length=40)),
                ('fechainicio', models.CharField(max_length=20)),
                ('fechafinal', models.CharField(max_length=20)),
                ('valor', models.CharField(max_length=20)),
                ('ciudad_Transp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plantur.ciudades')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('nit_proveedor', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('direccion_proveedor', models.CharField(max_length=40)),
                ('telefono', models.CharField(max_length=30)),
                ('actividad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plantur.actividad')),
                ('ciudad_Prov', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plantur.ciudades')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=20)),
                ('fechainicio', models.CharField(max_length=20)),
                ('fechafinal', models.CharField(max_length=20)),
                ('cedula', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plantur.usuario')),
                ('ciudad_Plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plantur.ciudades')),
                ('nit_hotel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plantur.hoteles')),
                ('nit_proveedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plantur.proveedor')),
                ('nit_transporte', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plantur.transporte')),
                ('tipo_actividad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plantur.actividad')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('mediopago', models.CharField(max_length=40)),
                ('valor', models.CharField(max_length=20)),
                ('cedula', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plantur.usuario')),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plantur.plan')),
            ],
        ),
        migrations.AddField(
            model_name='actividad',
            name='ciudad_Act',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plantur.ciudades'),
        ),
    ]
